server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.php;

    location = /_health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location / {
        # Let October handle everything by default.
        # Any path not resolved by the router will return October's 404 page.
        rewrite ^/.*$ /index.php last;
    }

    # Pass the PHP scripts to FastCGI server
    location ~ ^/index.php {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Allowlist
    location ~ ^/(favicon\.ico|sitemap\.xml|robots\.txt|humans\.txt) { try_files $uri /index.php; }

    # Block all .dotfiles except well-known
    location ~ /\.(?!well-known).* { deny all; }

    ## Static Files
    location ~ ^/storage/app/(uploads/public|media|resources) { try_files $uri 404; }
    location ~ ^/storage/temp/public { try_files $uri 404; }
    location ~ ^/modules/.*/(assets|resources) { try_files $uri 404; }
    location ~ ^/modules/.*/(behaviors|widgets|formwidgets|reportwidgets)/.*/(assets|resources) { try_files $uri 404; }
    location ~ ^/plugins/.*/.*/(assets|resources) { try_files $uri 404; }
    location ~ ^/plugins/.*/.*/(behaviors|reportwidgets|formwidgets|widgets)/.*/(assets|resources) { try_files $uri 404; }
    location ~ ^/themes/.*/(?:assets|resources) { try_files $uri 404; }
}
